### ISSUE TITLE
Ignore livechat messages if you're not the room participant

### ISSUE THREAD

**Issue by nsdev0** [RocketChat/Rocket.Chat.js.SDK#30]
Case:
When a new Livechat starts, it is redirected directly to the bot. The bot can transfer chat to a live person on demand. But after this transfer he continues to listen this room and try to respond to clients messages.

Solve:
Ignore messages in Livechat room if bot is not the room participant.

**Comment by timkinnane** [comment]
@nsdev0 So the bot has `RESPOND_TO_LIVECHAT=true` but after the handover, it's removed from the room, but continues to receive messages?

Are you just using the bot in livechat? If so, you could try `LISTEN_ON_ALL_PUBLIC=false` - I have a feeling that if that's true, the logic just doesn't filter based on if the bot is in the room, instead applying only the other filters.

If that's the problem here, we probably either need to change the logic or the env variable name to make sure it's more clear.

**Comment by nsdev0** [comment]
@timkinnane My bad
I can't remember for what but I gave him the role livechat's manager.
That's why he kept getting messages in the transferred room,
